//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.MetierGestion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gestion.MetierGestion.Utilisateur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gestion.MetierGestion.Proprietaire))]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersonne {
            get {
                return this.IdPersonneField;
            }
            set {
                if ((this.IdPersonneField.Equals(value) != true)) {
                    this.IdPersonneField = value;
                    this.RaisePropertyChanged("IdPersonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPrenom {
            get {
                return this.NomPrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPrenomField, value) != true)) {
                    this.NomPrenomField = value;
                    this.RaisePropertyChanged("NomPrenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion.Model")]
    [System.SerializableAttribute()]
    public partial class Utilisateur : Gestion.MetierGestion.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotDePasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifiant {
            get {
                return this.IdentifiantField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifiantField, value) != true)) {
                    this.IdentifiantField = value;
                    this.RaisePropertyChanged("Identifiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proprietaire", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion.Model")]
    [System.SerializableAttribute()]
    public partial class Proprietaire : Gestion.MetierGestion.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RccmField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ninea {
            get {
                return this.NineaField;
            }
            set {
                if ((object.ReferenceEquals(this.NineaField, value) != true)) {
                    this.NineaField = value;
                    this.RaisePropertyChanged("Ninea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rccm {
            get {
                return this.RccmField;
            }
            set {
                if ((object.ReferenceEquals(this.RccmField, value) != true)) {
                    this.RccmField = value;
                    this.RaisePropertyChanged("Rccm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appartement", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion.Model")]
    [System.SerializableAttribute()]
    public partial class Appartement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseAppartementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> CapaciteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAppartementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdProprietaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTypeAppartementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NombrePieceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.MetierGestion.Proprietaire ProprietaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> SurfaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.MetierGestion.TypeAppartement TypeAppartementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresseAppartement {
            get {
                return this.AdresseAppartementField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseAppartementField, value) != true)) {
                    this.AdresseAppartementField = value;
                    this.RaisePropertyChanged("AdresseAppartement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Capacite {
            get {
                return this.CapaciteField;
            }
            set {
                if ((this.CapaciteField.Equals(value) != true)) {
                    this.CapaciteField = value;
                    this.RaisePropertyChanged("Capacite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponible {
            get {
                return this.DisponibleField;
            }
            set {
                if ((this.DisponibleField.Equals(value) != true)) {
                    this.DisponibleField = value;
                    this.RaisePropertyChanged("Disponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAppartement {
            get {
                return this.IdAppartementField;
            }
            set {
                if ((this.IdAppartementField.Equals(value) != true)) {
                    this.IdAppartementField = value;
                    this.RaisePropertyChanged("IdAppartement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdProprietaire {
            get {
                return this.IdProprietaireField;
            }
            set {
                if ((this.IdProprietaireField.Equals(value) != true)) {
                    this.IdProprietaireField = value;
                    this.RaisePropertyChanged("IdProprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTypeAppartement {
            get {
                return this.IdTypeAppartementField;
            }
            set {
                if ((this.IdTypeAppartementField.Equals(value) != true)) {
                    this.IdTypeAppartementField = value;
                    this.RaisePropertyChanged("IdTypeAppartement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NombrePiece {
            get {
                return this.NombrePieceField;
            }
            set {
                if ((this.NombrePieceField.Equals(value) != true)) {
                    this.NombrePieceField = value;
                    this.RaisePropertyChanged("NombrePiece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.MetierGestion.Proprietaire Proprietaire {
            get {
                return this.ProprietaireField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietaireField, value) != true)) {
                    this.ProprietaireField = value;
                    this.RaisePropertyChanged("Proprietaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Surface {
            get {
                return this.SurfaceField;
            }
            set {
                if ((this.SurfaceField.Equals(value) != true)) {
                    this.SurfaceField = value;
                    this.RaisePropertyChanged("Surface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.MetierGestion.TypeAppartement TypeAppartement {
            get {
                return this.TypeAppartementField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeAppartementField, value) != true)) {
                    this.TypeAppartementField = value;
                    this.RaisePropertyChanged("TypeAppartement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeAppartement", Namespace="http://schemas.datacontract.org/2004/07/MetierGestion.Model")]
    [System.SerializableAttribute()]
    public partial class TypeAppartement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.MetierGestion.Appartement[] AppartementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTypeAppartementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleTypeAppartementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.MetierGestion.Appartement[] Appartements {
            get {
                return this.AppartementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppartementsField, value) != true)) {
                    this.AppartementsField = value;
                    this.RaisePropertyChanged("Appartements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTypeAppartement {
            get {
                return this.IdTypeAppartementField;
            }
            set {
                if ((this.IdTypeAppartementField.Equals(value) != true)) {
                    this.IdTypeAppartementField = value;
                    this.RaisePropertyChanged("IdTypeAppartement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleTypeAppartement {
            get {
                return this.LibelleTypeAppartementField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleTypeAppartementField, value) != true)) {
                    this.LibelleTypeAppartementField = value;
                    this.RaisePropertyChanged("LibelleTypeAppartement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetierGestion.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Gestion.MetierGestion.CompositeType GetDataUsingDataContract(Gestion.MetierGestion.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.CompositeType> GetDataUsingDataContractAsync(Gestion.MetierGestion.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProprietaire", ReplyAction="http://tempuri.org/IService1/AddProprietaireResponse")]
        bool AddProprietaire(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProprietaire", ReplyAction="http://tempuri.org/IService1/AddProprietaireResponse")]
        System.Threading.Tasks.Task<bool> AddProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeProprietaires", ReplyAction="http://tempuri.org/IService1/GetListeProprietairesResponse")]
        Gestion.MetierGestion.Proprietaire[] GetListeProprietaires(string nom, string telephone, string email, string ninea, string rccm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeProprietaires", ReplyAction="http://tempuri.org/IService1/GetListeProprietairesResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Proprietaire[]> GetListeProprietairesAsync(string nom, string telephone, string email, string ninea, string rccm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProprietaireById", ReplyAction="http://tempuri.org/IService1/GetProprietaireByIdResponse")]
        Gestion.MetierGestion.Proprietaire GetProprietaireById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProprietaireById", ReplyAction="http://tempuri.org/IService1/GetProprietaireByIdResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Proprietaire> GetProprietaireByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProprietaire", ReplyAction="http://tempuri.org/IService1/DeleteProprietaireResponse")]
        bool DeleteProprietaire(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProprietaire", ReplyAction="http://tempuri.org/IService1/DeleteProprietaireResponse")]
        System.Threading.Tasks.Task<bool> DeleteProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProprietaire", ReplyAction="http://tempuri.org/IService1/UpdateProprietaireResponse")]
        bool UpdateProprietaire(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProprietaire", ReplyAction="http://tempuri.org/IService1/UpdateProprietaireResponse")]
        System.Threading.Tasks.Task<bool> UpdateProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAppartement", ReplyAction="http://tempuri.org/IService1/AddAppartementResponse")]
        bool AddAppartement(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAppartement", ReplyAction="http://tempuri.org/IService1/AddAppartementResponse")]
        System.Threading.Tasks.Task<bool> AddAppartementAsync(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUtilisateur", ReplyAction="http://tempuri.org/IService1/AddUtilisateurResponse")]
        bool AddUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUtilisateur", ReplyAction="http://tempuri.org/IService1/AddUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> AddUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeAppartement", ReplyAction="http://tempuri.org/IService1/GetListeAppartementResponse")]
        Gestion.MetierGestion.Appartement[] GetListeAppartement(string adresse, System.Nullable<float> capacite, System.Nullable<bool> disponible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListeAppartement", ReplyAction="http://tempuri.org/IService1/GetListeAppartementResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement[]> GetListeAppartementAsync(string adresse, System.Nullable<float> capacite, System.Nullable<bool> disponible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListUtilisateurs", ReplyAction="http://tempuri.org/IService1/GetListUtilisateursResponse")]
        Gestion.MetierGestion.Utilisateur[] GetListUtilisateurs(string nom, string identifiant, string email, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListUtilisateurs", ReplyAction="http://tempuri.org/IService1/GetListUtilisateursResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Utilisateur[]> GetListUtilisateursAsync(string nom, string identifiant, string email, string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUtilisateurById", ReplyAction="http://tempuri.org/IService1/GetUtilisateurByIdResponse")]
        Gestion.MetierGestion.Utilisateur GetUtilisateurById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUtilisateurById", ReplyAction="http://tempuri.org/IService1/GetUtilisateurByIdResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Utilisateur> GetUtilisateurByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListAppartementByUserId", ReplyAction="http://tempuri.org/IService1/GetListAppartementByUserIdResponse")]
        Gestion.MetierGestion.Appartement[] GetListAppartementByUserId(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListAppartementByUserId", ReplyAction="http://tempuri.org/IService1/GetListAppartementByUserIdResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement[]> GetListAppartementByUserIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAppartementById", ReplyAction="http://tempuri.org/IService1/GetAppartementByIdResponse")]
        Gestion.MetierGestion.Appartement GetAppartementById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAppartementById", ReplyAction="http://tempuri.org/IService1/GetAppartementByIdResponse")]
        System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement> GetAppartementByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAppartement", ReplyAction="http://tempuri.org/IService1/DeleteAppartementResponse")]
        bool DeleteAppartement(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAppartement", ReplyAction="http://tempuri.org/IService1/DeleteAppartementResponse")]
        System.Threading.Tasks.Task<bool> DeleteAppartementAsync(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUtilisateur", ReplyAction="http://tempuri.org/IService1/DeleteUtilisateurResponse")]
        bool DeleteUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUtilisateur", ReplyAction="http://tempuri.org/IService1/DeleteUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> DeleteUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAppartement", ReplyAction="http://tempuri.org/IService1/UpdateAppartementResponse")]
        bool UpdateAppartement(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAppartement", ReplyAction="http://tempuri.org/IService1/UpdateAppartementResponse")]
        System.Threading.Tasks.Task<bool> UpdateAppartementAsync(Gestion.MetierGestion.Appartement appartement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUtilisateur", ReplyAction="http://tempuri.org/IService1/UpdateUtilisateurResponse")]
        bool UpdateUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUtilisateur", ReplyAction="http://tempuri.org/IService1/UpdateUtilisateurResponse")]
        System.Threading.Tasks.Task<bool> UpdateUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Gestion.MetierGestion.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Gestion.MetierGestion.IService1>, Gestion.MetierGestion.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Gestion.MetierGestion.CompositeType GetDataUsingDataContract(Gestion.MetierGestion.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.CompositeType> GetDataUsingDataContractAsync(Gestion.MetierGestion.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool AddProprietaire(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.AddProprietaire(proprietaire);
        }
        
        public System.Threading.Tasks.Task<bool> AddProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.AddProprietaireAsync(proprietaire);
        }
        
        public Gestion.MetierGestion.Proprietaire[] GetListeProprietaires(string nom, string telephone, string email, string ninea, string rccm) {
            return base.Channel.GetListeProprietaires(nom, telephone, email, ninea, rccm);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Proprietaire[]> GetListeProprietairesAsync(string nom, string telephone, string email, string ninea, string rccm) {
            return base.Channel.GetListeProprietairesAsync(nom, telephone, email, ninea, rccm);
        }
        
        public Gestion.MetierGestion.Proprietaire GetProprietaireById(System.Nullable<int> id) {
            return base.Channel.GetProprietaireById(id);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Proprietaire> GetProprietaireByIdAsync(System.Nullable<int> id) {
            return base.Channel.GetProprietaireByIdAsync(id);
        }
        
        public bool DeleteProprietaire(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.DeleteProprietaire(proprietaire);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.DeleteProprietaireAsync(proprietaire);
        }
        
        public bool UpdateProprietaire(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.UpdateProprietaire(proprietaire);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProprietaireAsync(Gestion.MetierGestion.Proprietaire proprietaire) {
            return base.Channel.UpdateProprietaireAsync(proprietaire);
        }
        
        public bool AddAppartement(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.AddAppartement(appartement);
        }
        
        public System.Threading.Tasks.Task<bool> AddAppartementAsync(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.AddAppartementAsync(appartement);
        }
        
        public bool AddUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.AddUtilisateur(utilisateur);
        }
        
        public System.Threading.Tasks.Task<bool> AddUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.AddUtilisateurAsync(utilisateur);
        }
        
        public Gestion.MetierGestion.Appartement[] GetListeAppartement(string adresse, System.Nullable<float> capacite, System.Nullable<bool> disponible) {
            return base.Channel.GetListeAppartement(adresse, capacite, disponible);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement[]> GetListeAppartementAsync(string adresse, System.Nullable<float> capacite, System.Nullable<bool> disponible) {
            return base.Channel.GetListeAppartementAsync(adresse, capacite, disponible);
        }
        
        public Gestion.MetierGestion.Utilisateur[] GetListUtilisateurs(string nom, string identifiant, string email, string telephone) {
            return base.Channel.GetListUtilisateurs(nom, identifiant, email, telephone);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Utilisateur[]> GetListUtilisateursAsync(string nom, string identifiant, string email, string telephone) {
            return base.Channel.GetListUtilisateursAsync(nom, identifiant, email, telephone);
        }
        
        public Gestion.MetierGestion.Utilisateur GetUtilisateurById(System.Nullable<int> id) {
            return base.Channel.GetUtilisateurById(id);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Utilisateur> GetUtilisateurByIdAsync(System.Nullable<int> id) {
            return base.Channel.GetUtilisateurByIdAsync(id);
        }
        
        public Gestion.MetierGestion.Appartement[] GetListAppartementByUserId(System.Nullable<int> id) {
            return base.Channel.GetListAppartementByUserId(id);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement[]> GetListAppartementByUserIdAsync(System.Nullable<int> id) {
            return base.Channel.GetListAppartementByUserIdAsync(id);
        }
        
        public Gestion.MetierGestion.Appartement GetAppartementById(System.Nullable<int> id) {
            return base.Channel.GetAppartementById(id);
        }
        
        public System.Threading.Tasks.Task<Gestion.MetierGestion.Appartement> GetAppartementByIdAsync(System.Nullable<int> id) {
            return base.Channel.GetAppartementByIdAsync(id);
        }
        
        public bool DeleteAppartement(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.DeleteAppartement(appartement);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAppartementAsync(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.DeleteAppartementAsync(appartement);
        }
        
        public bool DeleteUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.DeleteUtilisateur(utilisateur);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.DeleteUtilisateurAsync(utilisateur);
        }
        
        public bool UpdateAppartement(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.UpdateAppartement(appartement);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAppartementAsync(Gestion.MetierGestion.Appartement appartement) {
            return base.Channel.UpdateAppartementAsync(appartement);
        }
        
        public bool UpdateUtilisateur(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.UpdateUtilisateur(utilisateur);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUtilisateurAsync(Gestion.MetierGestion.Utilisateur utilisateur) {
            return base.Channel.UpdateUtilisateurAsync(utilisateur);
        }
    }
}
